function plot_morphing_sim_logs()
% =========================================================================
% OMNIDESIGN OPTIMIZER - DYNAMIC RECONFIGURATION TELEMETRY PLOTTER
% =========================================================================
% Description:
%   This script processes the telemetry logs ('morphing_sim_log.mat') 
%   generated by the interactive dynamic reconfiguration simulator. 
%   It produces a publication-ready, vertically stacked time-series figure 
%   to empirically validate two core theoretical claims:
%
%   1. Control Effort Invariance: Proving that traversing the 1D optimal 
%      manifold (lambda) requires zero additional control effort (||f|| is 
%      strictly constant), confirming true zero-energy self-motion.
%   2. Aerodynamic Wake Vectoring: Quantifying the practical utility of the 
%      null space by tracking environmental particle advection (wake sweeping).
%
% License: MIT / Academic Free License
% =========================================================================
    
    %% --- 1. Data Ingestion & Validation ---
    if ~isfile('morphing_sim_log.mat')
        error('Log file not found. Please run the ''hexarotor_morphing_animation'' script first and click ''Stop & Save'' to generate the telemetry data.');
    end
    
    % Loads: log_t, log_lambda, log_f, log_norm_f, log_particles
    load('morphing_sim_log.mat'); 
    
    %% --- 2. Plotting Configuration & Windowing ---
    % Define the temporal window to extract for the publication figure
    t_start = 0;         % Start time (seconds)
    t_end   = inf;       % End time (seconds). Use 'inf' for full duration
    
    % Core styling parameters for high-dpi academic printing
    font_size   = 12;
    line_width  = 1.5;
    
    % Create a standard colormap palette matching the simulation (Hexarotor)
    colors = lines(6);   
    
    %% --- 3. Data Extraction & Filtering ---
    idx = (log_t >= t_start) & (log_t <= t_end);
    
    t   = log_t(idx);
    lam = log_lambda(idx);
    f   = log_f(:, idx);
    nf  = log_norm_f(idx);
    p_c = log_particles(idx);
    
    if isempty(t)
        error('No data found in the specified temporal window [%.1f, %.1f].', t_start, t_end);
    end
    
    %% --- 4. Publication-Ready Figure Generation ---
    % Figure Setup (Targeting an approximate 1.8:1 Aspect Ratio)
    fig = figure('Name', 'Morphing Simulation Telemetry', 'Color', 'w', ...
                 'Position', [100, 100, 900, 500]);
                 
    % Using tiledlayout ensures subplots pack tightly and align perfectly on the X-axis
    tl = tiledlayout(4, 1, 'TileSpacing', 'compact', 'Padding', 'compact');
    
    % --- Subplot 1: Morphological State Parameter (\lambda) ---
    ax1 = nexttile;
    plot(ax1, t, lam, 'k', 'LineWidth', line_width);
    ylabel(ax1, '\lambda (rad)', 'FontSize', font_size, 'FontWeight', 'bold');
    grid(ax1, 'on'); 
    set(ax1, 'FontSize', font_size, 'XTickLabel', []);
    
    % --- Subplot 2: Individual Propeller Thrust Forces ---
    ax2 = nexttile; hold(ax2, 'on');
    for i = 1:6
        plot(ax2, t, f(i,:), 'Color', colors(i,:), 'LineWidth', line_width);
    end
    ylabel(ax2, 'Rotor Forces (N)', 'FontSize', font_size, 'FontWeight', 'bold');
    grid(ax2, 'on');
    set(ax2, 'FontSize', font_size, 'XTickLabel', []);
    
    % --- Subplot 3: Total Omnidirectional Control Effort (L2 Norm) ---
    % Critical empirical proof: This line MUST remain flat.
    ax3 = nexttile;
    plot(ax3, t, nf, 'Color', [0.3 0.3 0.3], 'LineWidth', line_width + 0.5);
    ylabel(ax3, '||f|| (N)', 'FontSize', font_size, 'FontWeight', 'bold');
    grid(ax3, 'on');
    set(ax3, 'FontSize', font_size, 'XTickLabel